#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  killall -TERM irssi 2>/dev/null
}

trap _term SIGTERM

export HOME="/config"
screen -OaDmS irssi \
  -T xterm-256color \
  s6-setuidgid abc /usr/bin/irssi --home /config/.irssi &

wait
