#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  killall -TERM irssi 2>/dev/null
}

trap _term SIGTERM

export TERM="xterm-256color"
screen -c /config/.screenrc \
  -D -m -S irssi \
  s6-setuidgid abc /usr/bin/irssi-bin &

wait
