#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  killall -TERM irssi 2>/dev/null
}

trap _term SIGTERM

export HOME="/config"
#screen -D -m -S irssi s6-setuidgid abc /usr/bin/irssi --home /config/.irssi &
tmux -2 -d new-window \
  -n irssi \
  -s autodl-irssi \
  "s6-setuidgid abc /usr/bin/irssi --home /config/.irssi" &

wait
