#!/usr/bin/with-contenv bash

# configure screen
[[ ! -f /config/.screenrc ]] && \
  cp -v /defaults/screenrc /config/.screenrc

# install irssi, perl with dependancies and php7-sockets
if [ ! -e /usr/bin/irssi ]; then
  echo "**** irssi not found - installing ****"
  apk add --no-cache --upgrade \
    php7-sockets \
    irssi-perl \
    perl \
    perl-archive-zip \
    perl-net-ssleay \
    perl-html-parser \
    perl-xml-libxml \
    perl-digest-sha1 \
    perl-json \
    perl-json-xs
  if [ ! -d /config/.irssi ]; then
      # first time setup (enable perl for scripts)
    mkdir -p /config/.irssi
    echo 'load perl' > /config/.irssi/startup
  fi
  cp /defaults/irssi-bin \
    /usr/bin/irssi-bin
  chmod +x /usr/bin/irssi-bin
else
  echo "**** irssi found - skipping ****"
    # recreate container to update
fi

# install autodl-irssi script
if [ ! -e /config/.irssi/scripts/autorun/autodl-irssi.pl ] && \
   [ ! -d /config/plugins/autodl-irssi ]; then
  adlport=$(shuf -i 60000-65000 -n 1)
  adlpass=$(openssl rand -base64 20)
  echo "**** autodl-irssi not found - installing ****"
  mkdir -p /config/.irssi/scripts/autorun
  AUTODL_URL=$(curl -sLX GET "https://api.github.com/repos/autodl-community/autodl-irssi/releases/latest" \
    | awk '/browser_download_url/{print $4;exit}' FS='[""]')
  wget -q \
    -O /config/.irssi/scripts/autodl-irssi.zip \
    ${AUTODL_URL}
  unzip -d /config/.irssi/scripts \
    -o /config/.irssi/scripts/autodl-irssi.zip
  rm -f /config/.irssi/scripts/autodl-irssi.zip
  cp -v /config/.irssi/scripts/autodl-irssi.pl \
    /config/.irssi/scripts/autorun/
  mkdir -p /config/.autodl
  cat /defaults/autodl.cfg \
    | sed "s|gui-server-password = adlpass|gui-server-password = ${adlpass}|; s|gui-server-port = adlport|gui-server-port = ${adlport}|" \
    | tee /config/.autodl/autodl.cfg
  echo "**** autodl-irssi rutorrent plugin not found - installing ****"
  if [ ! -d /config/plugins ]; then
    mkdir -p /config/plugins
    chown abc:abc /config/plugins
  fi
  git clone https://github.com/autodl-community/autodl-rutorrent.git \
    /config/plugins/autodl-irssi
  cat /defaults/conf.php \
    | sed "s|\$autodlPort = adlport;|\$autodlPort = ${adlport};|; s|\$autodlPassword = \"adlpass\";|\$autodlPassword = \"${adlpass}\";|" \
    | tee /config/plugins/autodl-irssi/conf.php
  unset adlport
  unset adlpass
elif [ -d /config/plugins/autodl-irssi ]; then
  # autodl-irssi setup to auto-update in config
  # autodl-irssi rutorrent plugin updates from git
  echo "**** autodl-irssi found - updating rutorrent plugin ****"
  git -C /config/plugins/autodl-irssi pull --ff-only
fi

# set correct permissions
chown abc:abc -R /config/{.autodl,.irssi,.screenrc,plugins/autodl-irssi}

# install/update plugin
cp -aR /config/plugins/autodl-irssi /app/rutorrent/plugins/
