#!/usr/bin/with-contenv bash

# configure screen
[[ ! -f /config/.screenrc ]] && \
  cp -v /defaults/screenrc /config/.screenrc

# install irssi, perl with dependancies and php7-sockets
if [ ! -e /usr/bin/irssi ]; then
  echo "**** irssi not found - installing ****"
  apk add --no-cache --upgrade \
    php7-sockets \
    irssi-perl \
    perl \
    perl-archive-zip \
    perl-net-ssleay \
    perl-html-parser \
    perl-xml-libxml \
    perl-digest-sha1 \
    perl-json \
    perl-json-xs
  if [ ! -d /config/.irssi ]; then
      # first time setup (enable perl for scripts)
    mkdir -p /config/.irssi
    echo 'load perl' > /config/.irssi/startup
  fi
else
  echo "**** irssi found - skipping ****"
    # recreate container to update
fi

# install autodl-irssi script
if [ ! -e /config/.irssi/scripts/autorun/autodl-irssi.pl ] && \
   [ ! -d /config/plugins/autodl-irssi ]; then
  adlpass=$(openssl rand -base64 20)
  echo "**** autodl-irssi not found - installing ****"
  mkdir -p /config/.irssi/scripts/autorun
  AUTODL_URL=$(curl -sLX GET "https://api.github.com/repos/autodl-community/autodl-irssi/releases/latest" \
    | awk '/browser_download_url/{print $4;exit}' FS='[""]')
  wget -q \
    -O /config/.irssi/scripts/autodl-irssi.zip \
    ${AUTODL_URL}
  unzip -d /config/.irssi/scripts \
    -o /config/.irssi/scripts/autodl-irssi.zip
  rm -f /config/.irssi/scripts/autodl-irssi.zip
  cp -v /config/.irssi/scripts/autodl-irssi.pl \
    /config/.irssi/scripts/autorun/
  mkdir -p /config/.autodl
  cat << EOL > /config/.autodl/autodl.cfg
[options]
rt-address = /run/php/.rtorrent.sock
gui-server-port = 64450
gui-server-password = $adlpass
update-check = auto
EOL
  echo "**** autodl-irssi rutorrent plugin not found - installing ****"
  if [ ! -d /config/plugins ]; then
    mkdir -p /config/plugins
    chown abc:abc /config/plugins
  fi
  git clone https://github.com/autodl-community/autodl-rutorrent.git \
    /config/plugins/autodl-irssi
  cat << EOL > /config/plugins/autodl-irssi/conf.php
<?php
\$autodlPort = 64450;
\$autodlPassword = "$adlpass";
?>
EOL
  unset adlpass
elif [ -d /config/plugins/autodl-irssi ]; then
  echo "**** autodl-irssi found - updating rutorrent plugin ****"
    # autodl-irssi setup to auto-update in config
    # autodl-irssi rutorrent plugin updates from git
  git -C /config/plugins/autodl-irssi pull --ff-only
fi

# set correct permissions
chown abc:abc -R /config/{.autodl,.irssi,.screenrc,plugins/autodl-irssi}

# install/update plugin
cp -aR /config/plugins/autodl-irssi /app/rutorrent/plugins/
