#!/usr/bin/with-contenv bash

# install java and other dependancies
if [ ! -e /usr/bin/java ]; then
  echo "**** java not found - installing ****"
  apt-get update -y -q
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    default-jre-headless \
    libjna-java \
    libcurl3-gnutls \
    libmms0 \
    libchromaprint-tools \
    p7zip-rar \
    mkvtoolnix \
    mp4v2-utils \
    inotify-tools
else
  echo "**** java found - skipping install ****"
fi

# install filebot
if [ ! -e /usr/bin/filebot ]; then
  echo "**** filebot not found - installing ****"
  APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key adv --fetch-keys \
    https://raw.githubusercontent.com/filebot/plugins/master/gpg/maintainer.pub
  echo "deb [arch=all] https://get.filebot.net/deb/ universal main" > /etc/apt/sources.list.d/filebot.list
  apt-get update -y -q
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends filebot
  mv /usr/bin/filebot /usr/bin/filebot-bin
  cat << EOL > /usr/bin/filebot
#!/usr/bin/with-contenv bash
HOME=/config exec /usr/bin/filebot-bin "$@"
EOL
  chmod +x /usr/bin/filebot
else
  echo "**** filebot found - skipping install ****"
fi

# install mediainfo
if [ ! -e /usr/bin/mediainfo ]; then
  echo "**** mediainfo / libzen not found - installing ****"
  # get latest mediainfo / libzen versions
  MEDIAINFO_VERSION=$(curl -sLX GET https://api.github.com/repos/MediaArea/MediaInfo/releases/latest \
    | awk '/tag_name/{print $4;exit}' FS='[""]')
  LIBZEN_VERSION=$(curl -sLX GET https://api.github.com/repos/MediaArea/ZenLib/releases/latest \
    | awk '/tag_name/{print $4;exit}' FS='[""]')

  # mediainfo and libzen packages
  MEDIAINFO_PACKAGE="mediainfo_${MEDIAINFO_VERSION:1}-1_amd64.xUbuntu_18.04.deb"
  LIBMEDIAINFO_PACKAGE="libmediainfo0v5_${MEDIAINFO_VERSION:1}-1_amd64.xUbuntu_18.04.deb"
  LIBZEN_PACKAGE="libzen0v5_${LIBZEN_VERSION:1}-1_amd64.xUbuntu_18.04.deb"

  # install mediainfo and libzen
  mkdir -p /mediainfo
  curl -o /mediainfo/mediainfo.deb \
   -L "https://mediaarea.net/download/binary/mediainfo/${MEDIAINFO_VERSION:1}/${MEDIAINFO_PACKAGE}"
  curl -o /mediainfo/libmediainfo.deb \
   -L "https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION:1}/${LIBMEDIAINFO_PACKAGE}"
  curl -o /mediainfo/libzen.deb \
   -L "https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION:1}/${LIBZEN_PACKAGE}"
  dpkg -i /mediainfo/{libzen.deb,libmediainfo.deb,mediainfo.deb}
  rm -rf /mediainfo
else
  echo "**** mediainfo / libzen found - skipping install"
fi

# clean-up
rm -rf \
  /tmp/* \
  /var/tmp/* \
  /var/lib/apt/lists/*

# confirm filebot install
echo "**** exec \"filebot -script fn:sysinfo\" ****"
exec s6-setuidgid abc filebot -script fn:sysinfo
