#!/usr/bin/with-contenv bash

# generate random password for initial plug-in setup
adlpass=$(openssl rand -base64 20)

# install irssi with perl dependancies and php7-sockets
if [ ! -e /usr/bin/irssi ]; then
  echo "**** irssi not found - installing ****"
  apk add --no-cache --upgrade \
    php7-sockets \
    grep \
    irssi-perl \
    perl \
    perl-archive-zip \
    perl-net-ssleay \
    perl-html-parser \
    perl-xml-libxml \
    perl-digest-sha1 \
    perl-json \
    perl-json-xs
  if [ ! -d /config/.irssi ]; then
    mkdir -p /config/.irssi && \
      touch /config/.irssi/startup
    echo 'load perl' > /config/.irssi/startup
  fi
else
  echo "**** irssi found - skipping ****"
fi

# install autodl-irssi
if [ ! -e /config/.irssi/scripts/autorun/autodl-irssi.pl ]; then
  echo "**** autodl-irssi not found - installing ****"
  mkdir -p /config/.irssi/scripts/autorun
  cd /config/.irssi/scripts
  AUTODL_URL=$(curl -sL \
    https://api.github.com/repos/autodl-community/autodl-irssi/releases/latest | \
    grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)')
  wget --quiet -O autodl-irssi.zip $AUTODL_URL
  unzip -q -o autodl-irssi.zip
  rm -f autodl-irssi.zip
  cp autodl-irssi.pl autorun/
  mkdir -p /config/.autodl
  cat << EOL > /config/.autodl/autodl.cfg
[options]
update-check = auto
rt-address = /run/php/.rtorrent.sock
gui-server-port = 54450
gui-server-password = $adlpass
EOL
else
  echo "**** autodl-irssi found - skipping ****"
fi

# install/update rutorrent autodl-irssi plugin
if [ ! -d /config/plugins/autodl-irssi ]; then
  echo "**** autodl-irssi rutorrent plugin not found - installing ****"
  [ -d /config/plugins ] || \
    mkdir -p /config/plugins && \
    chown abc:abc /config/plugins
  cd /config/plugins
  git clone https://github.com/autodl-community/autodl-rutorrent.git autodl-irssi
  cat << EOL > /config/plugins/autodl-irssi/conf.php
<?php
\$autodlPort = 54450;
\$autodlPassword = "$adlpass";
?>
EOL
elif [ -d /config/plugins/autodl-irssi ]; then
  echo "**** autodl-irssi rutorrent plugin found - updating ****"
  cd /config/plugins/autodl-irssi
  git pull --ff-only
fi

unset adlpass

# set permissions correctly
chown abc:abc -R /config/{.autodl,.irssi,plugins/autodl-irssi}

# install plugin/updates
cp -aR /config/plugins/autodl-irssi /app/rutorrent/plugins/

