#!/usr/bin/with-contenv bash

# set home for irssi files
export HOME=/config

# generate random password for initial plug-in setup
adlpass=$(openssl rand -base64 20)

# install irssi with perl dependancies and php7-sockets
if [ ! -e /usr/bin/irssi ]; then
  echo "**** irssi not found - installing ****"
  apk add --no-cache --upgrade \
    php7-sockets \
    irssi-perl \
    perl jq \
    perl-archive-zip \
    perl-net-ssleay \
    perl-html-parser \
    perl-xml-libxml \
    perl-digest-sha1 \
    perl-json \
    perl-json-xs
  if [ ! -d /config/.irssi ]; then
    mkdir -p /config/.irssi
    echo 'load perl' > /config/.irssi/startup
  fi
else
  echo "**** irssi found - skipping ****"
  # recreate container to update
fi

# install autodl-irssi
if [ ! -e /config/.irssi/scripts/autorun/autodl-irssi.pl ]; then
  AUTODL_REL=$(curl -s https://api.github.com/repos/autodl-community/autodl-irssi/releases/latest)
  AUTODL_VER=$(echo ${AUTODL_REL} | jq -r '.tag_name')
  AUTODL_URL=$(echo ${AUTODL_REL} | jq -r '.assets[].browser_download_url')
  echo "**** autodl-irssi not found - installing v${AUTODL_VER} ****"
  mkdir -p /config/.irssi/scripts/autorun
  wget -q \
    -O /config/.irssi/scripts/autodl-irssi.zip \
    ${AUTODL_URL}
  unzip -q \
    -d /config/.irssi/scripts \
    -o /config/.irssi/scripts/autodl-irssi.zip
  rm -f /config/.irssi/scripts/autodl-irssi.zip
  cp /config/.irssi/scripts/autodl-irssi.pl \
     /config/.irssi/scripts/autorun/
  mkdir -p /config/.autodl
  cat << EOL > /config/.autodl/autodl.cfg
[options]
update-check = auto
rt-address = /run/php/.rtorrent.sock
gui-server-port = 54450
gui-server-password = $adlpass
EOL
else
  echo "**** autodl-irssi found - skipping ****"
  # configured to auto-update in options
fi

# install/update rutorrent autodl-irssi plugin
if [ ! -d /config/plugins/autodl-irssi ]; then
  echo "**** autodl-irssi rutorrent plugin not found - installing ****"
  if [ ! -d /config/plugins ]; then
    mkdir -p /config/plugins
    chown abc:abc /config/plugins
  fi
  git clone https://github.com/autodl-community/autodl-rutorrent.git \
    /config/plugins/autodl-irssi
  cat << EOL > /config/plugins/autodl-irssi/conf.php
<?php
\$autodlPort = 54450;
\$autodlPassword = "$adlpass";
?>
EOL
elif [ -d /config/plugins/autodl-irssi ]; then
  echo "**** autodl-irssi rutorrent plugin found - running update ****"
  git -C /config/plugins/autodl-irssi pull --ff-only
fi

# unset generated password
unset adlpass

# set correct permissions
chown abc:abc -R /config/{.autodl,.irssi,plugins/autodl-irssi}

# install/update plugin
cp -aR /config/plugins/autodl-irssi /app/rutorrent/plugins/
