#!/usr/bin/with-contenv bash

# install/update theme
if [ ! -d /config/themes/club-QuickBox ]; then
  echo "**** club-QuickBox theme not found - installing ****"
  if [ ! -d /config/themes ]; then
    mkdir -p /config/themes
    chown abc:abc /config/themes
  fi
  git clone https://github.com/QuickBox/club-QuickBox.git \
    /config/themes/club-QuickBox
elif [ -d /config/themes/club-QuickBox ]; then
  echo "**** club-QuickBox theme found - running update ****"
  git -C /config/themes/club-QuickBox pull --ff-only
fi

# set correct permissions
chown abc:abc -R /config/themes/club-QuickBox

# install/update theme
cp -aR /config/themes/club-QuickBox /app/rutorrent/plugins/theme/themes
